name: Udaconnect Locations API - Package with Docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push locations-api
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./modules/locations-api
          file: ./modules/locations-api/Dockerfile
          push: true
          tags: jstaley6/udaconnect-locations:latest
          platforms: linux/amd64
      -
        name: Build and push persons-api
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./modules/persons-api
          file: ./modules/persons-api/Dockerfile
          push: true
          tags: jstaley6/udaconnect-persons:latest
          platforms: linux/amd64
      -
        name: Build and push frontend
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend
          file: ./modules/frontened/Dockerfile
          push: true
          tags: jstaley6/udaconnect-frontend:latest
          platforms: linux/amd64